version: '3.8'

services:
  # React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
    networks:
      - app
    depends_on:
      - backend
      - mysql

  # Laravel Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/app/backend
    networks:
      - app
    depends_on:
      - mysql

  # MySQL Service
  mysql:
    image: mysql:8.0.21
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: finance_payment
      MYSQL_ROOT_PASSWORD: Ipsos!2025
      MYSQL_USER: root
      MYSQL_PASSWORD: Ipsos!2025
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app

# Volumes
volumes:
  mysql-data:

# Networks
networks:
  app:
    driver: bridge
